import { readFile, readdir, mkdir, writeFile, rm } from 'node:fs/promises';
import { join } from 'node:path';

const root = process.cwd();
const source = join(root, 'blog/data');
const blog = join(root, 'blog');
const templatePath = join(blog, 'when-to-replace-your-roof-denver-nc/index.html');
const listingPath = join(blog, 'index.html');
const origin = 'https://cprhomepros.com/blog/';
const pageMarker = '<!-- Generated by Ryze; edit the article JSON, not this page. -->';
const start = '<!-- RYZE ARTICLES START -->';
const end = '<!-- RYZE ARTICLES END -->';
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);

function replaceOne(html, pattern, replacement, label) {
  const matches = [...html.matchAll(new RegExp(pattern.source, pattern.flags.includes('g') ? pattern.flags : pattern.flags + 'g'))];
  if (matches.length !== 1) throw new Error(`Expected one ${label} in existing blog template; found ${matches.length}`);
  return html.replace(pattern, replacement);
}

const template = await readFile(templatePath, 'utf8');
let listing = await readFile(listingPath, 'utf8');
const records = [];
let filenames = [];
try { filenames = (await readdir(source)).filter(name => name.endsWith('.json')).sort(); }
catch (error) { if (error.code !== 'ENOENT') throw error; }

for (const filename of filenames) {
  const article = JSON.parse(await readFile(join(source, filename), 'utf8'));
  if (article.status !== 'published') continue;
  const slug = article.slug;
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug) || filename !== `${slug}.json`) throw new Error(`Invalid or mismatched article slug: ${filename}`);
  if (!article.title || !article.body_html) throw new Error(`Missing title or body_html: ${filename}`);
  const url = new URL(`${slug}/`, origin).href;
  const title = escapeHtml(article.title);
  const metaTitle = escapeHtml(article.meta_title || article.title);
  const description = escapeHtml(article.meta_description || article.excerpt || article.title);
  const excerpt = escapeHtml(article.excerpt || article.meta_description || '');
  const imageUrl = typeof article.image === 'object' && article.image !== null ? article.image.url : null;
  if (imageUrl && !/^https:\/\//.test(imageUrl)) throw new Error(`Image must use HTTPS: ${filename}`);
  const image = imageUrl ? `<figure style="margin:0 0 1.5rem"><img src="${escapeHtml(imageUrl)}" alt="${escapeHtml(article.image.alt || article.title)}" style="display:block;width:100%;height:auto;border-radius:0.5rem" loading="lazy"></figure>\n      ` : '';
  let html = template;
  html = replaceOne(html, /<title>[^<]*<\/title>/, `<title>${metaTitle}</title>`, 'title');
  html = replaceOne(html, /<meta name="description" content="[^"]*">/, `<meta name="description" content="${description}">`, 'meta description');
  html = replaceOne(html, /<link rel="canonical" href="[^"]*">/, `<link rel="canonical" href="${url}">`, 'canonical');
  html = replaceOne(html, /<meta property="og:image" content="[^"]*">/, `<meta property="og:image" content="${escapeHtml(imageUrl || 'https://cprhomepros.com/images/from-live/IMG_4733.JPG')}">`, 'social image');
  for (const [key, value] of [['url', url], ['description', description], ['title', metaTitle]]) {
    html = replaceOne(html, new RegExp(`<meta property="og:${key}" content="[^"]*">`), `<meta property="og:${key}" content="${value}">`, `og:${key}`);
  }
  html = replaceOne(html, /<section class="hero dual-hero compact">[\s\S]*?<\/section>/, `<section class="hero dual-hero compact">\n  <div class="wrap">\n    <p class="eyebrow hero-eyebrow"><a href="/blog/">Blog</a></p>\n    <h1>${title}</h1>\n    <p class="lead">${excerpt}</p>\n  </div>\n</section>`, 'article hero');
  html = replaceOne(html, /<article class="card" style="padding:1\.5rem 1\.75rem">[\s\S]*?<\/article>/, `<article class="card ryze-article" style="padding:1.5rem 1.75rem">\n      ${image}${article.body_html}\n      <p class="nap" style="margin-top:1.5rem"><strong>Campbell's Precision Roofing</strong> · Denver, NC 28037 · <a href="tel:+17042805996">(704) 280-5996</a></p>\n    </article>`, 'article body');
  html = replaceOne(html, /<div class="callout" style="margin:1\.5rem 0">[\s\S]*?<\/div>/, `<div class="callout" style="margin:1.5rem 0"><p><a href="/blog/">← More roofing articles</a> · <a href="/contact-us/#estimate">Request an estimate</a></p></div>`, 'related links');
  // Existing site CSS styles headings and lists; cover tables and embedded rich blocks as well.
  html = replaceOne(html, /<\/head>/, `<style>.ryze-article img{max-width:100%;height:auto}.ryze-article table{display:block;overflow-x:auto;border-collapse:collapse;width:100%}.ryze-article th,.ryze-article td{border:1px solid #ddd;padding:.65rem;text-align:left}.ryze-article blockquote{border-left:3px solid #B8975F;padding-left:1rem;margin-left:0}.ryze-article iframe{max-width:100%}</style>\n</head>`, 'head');
  html = html.replace('<!DOCTYPE html>', `<!DOCTYPE html>\n${pageMarker}`);
  const directory = join(blog, slug);
  const output = join(directory, 'index.html');
  let existing;
  try { existing = await readFile(output, 'utf8'); } catch (error) { if (error.code !== 'ENOENT') throw error; }
  if (existing && !existing.includes(pageMarker)) throw new Error(`Refusing to overwrite an existing manually maintained page: ${slug}`);
  await mkdir(directory, { recursive: true });
  if (existing !== html) await writeFile(output, html);
  records.push({ slug, title, excerpt, date: article.published_at || '' });
}

// Delete only pages this converter owns when their JSON was removed or unpublished.
const active = new Set(records.map(record => record.slug));
for (const entry of await readdir(blog, { withFileTypes: true })) {
  if (!entry.isDirectory() || entry.name === 'data' || active.has(entry.name)) continue;
  const output = join(blog, entry.name, 'index.html');
  let html;
  try { html = await readFile(output, 'utf8'); } catch (error) { if (error.code !== 'ENOENT') throw error; }
  if (html?.includes(pageMarker)) await rm(join(blog, entry.name), { recursive: true, force: true });
}

const oldBlock = new RegExp(`\\s*${start}[\\s\\S]*?${end}`);
listing = listing.replace(oldBlock, '');
const cards = records.sort((a, b) => b.date.localeCompare(a.date)).map(({ slug, title, excerpt }) => `    <div class="card" style="margin-bottom:1.25rem;padding:1.5rem 1.75rem">\n      <h2 style="margin-top:0;font-size:1.25rem"><a href="/blog/${slug}/">${title}</a></h2>\n      <p>${excerpt}</p>\n      <p><a href="/blog/${slug}/">Read post →</a></p>\n    </div>`).join('\n');
const insertion = `\n    ${start}\n${cards}\n    ${end}`;
listing = replaceOne(listing, /(<section>\s*<div class="wrap" style="max-width:48rem">)/, `$1${insertion}`, 'blog listing container');
await writeFile(listingPath, listing);
console.log(`Rendered ${records.length} Ryze article(s) and updated the blog listing.`);
